title: AZI Family Childcare
description: Your family childcare description
baseurl: ""
url: "https://azichildcare.com"

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - vendor
  - Gemfile
  - Gemfile.lock